### ISSUE TITLE
Polygon.isSelfIntersecting doesn't work at all

### ISSUE THREAD

**Issue by sroik** [toineheuvelmans/Metron#16]
U need to consider edge points

<img width="1341" alt="screen shot 2019-02-15 at 3 02 30 pm" src="https://user-images.githubusercontent.com/7701363/52855825-9e462100-3133-11e9-9a16-640b5b21b1ec.png">

**Comment by iby** [comment]
@toineheuvelmans This is caused by point reordering in the `init`: https://github.com/toineheuvelmans/Metron/blob/58a6c8945f3714c6d750e0f71be53c66d25733b0/source/Metron/Shape/Polygon.swift#L29-L53

I'm guessing `…certain calculations can be done more easily…` is about convex hull? Do you remember if there is anything else that relies on this?

**Comment by toineheuvelmans** [comment]
@sroik It ensures the points and thus line segments are in order. If I recall correctly this is indeed for calculating the convex hull but also for anything that iterates over the points / line segments, so `area`, `lineSegments`, `isConvex` and `path`.
